import type { IndustryPack, ParameterDefinition, PriceBookConfig, ResearchProjectTypeId } from "./models";

const recruitmentOptions = [
  { label: "普通大众", value: "general" },
  { label: "特定品牌或行为人群", value: "specific" },
  { label: "高价值或稀缺人群", value: "rare" },
];

const responsibilityOptions = [
  { label: "计入本方报价", value: "quoted" },
  { label: "客户提供", value: "client" },
  { label: "第三方直接提供", value: "third_party" },
  { label: "本项目不包含", value: "excluded" },
];

const deliveryCommon: ParameterDefinition[] = [
  { id: "projectCycleDays", label: "项目周期", dataType: "number", unit: "天", required: true },
  { id: "rushLevel", label: "加急程度", dataType: "singleSelect", required: true, options: [{ label: "正常周期", value: "normal" }, { label: "轻度加急", value: "rush" }, { label: "高度加急", value: "urgent" }] },
  { id: "reportDepth", label: "报告深度", dataType: "singleSelect", required: true, options: [{ label: "无需报告", value: "none" }, { label: "基础版", value: "basic" }, { label: "标准版", value: "standard" }, { label: "深度版", value: "deep" }] },
];

const commonWithAudience: ParameterDefinition[] = [
  { id: "targetAudience", label: "目标人群", dataType: "text", required: true },
  ...deliveryCommon,
];

export const researchIndustryPack: IndustryPack = {
  id: "research-industry",
  name: "调研行业包",
  version: 2,
  terminology: { focus_group: "焦点小组/座谈会", sample: "有效样本", incidenceRate: "目标人群筛选通过率" },
  projectTypes: [
    {
      id: "quantitative_online",
      name: "线上定量研究",
      shortDescription: "问卷、线上样本与数据分析的一体化测算",
      accent: "#4969f5",
      parameters: [
        { id: "sampleSize", label: "有效样本量", dataType: "number", unit: "份", required: true },
        { id: "incidenceRate", label: "目标人群筛选通过率", description: "每 100 名被筛选者中预计符合项目条件的人数", dataType: "percentage", unit: "%", required: true },
        { id: "questionnaireMinutes", label: "问卷时长", dataType: "number", unit: "分钟", required: true },
        { id: "questionnaireComplexity", label: "问卷复杂度", dataType: "singleSelect", required: true, options: [{ label: "简单逻辑", value: "simple" }, { label: "常规逻辑", value: "standard" }, { label: "复杂逻辑与素材", value: "complex" }] },
        { id: "quotaComplexity", label: "配额复杂度", dataType: "singleSelect", required: true, options: [{ label: "无复杂配额", value: "simple" }, { label: "多维交叉配额", value: "standard" }, { label: "严格小单元配额", value: "complex" }] },
        { id: "provinceCount", label: "覆盖省份", dataType: "number", unit: "个", required: true },
        ...commonWithAudience,
      ],
    },
    {
      id: "quantitative_offline",
      name: "线下定量研究",
      shortDescription: "拦截、入户、门店与产品测试的现场执行预算",
      accent: "#2784d6",
      parameters: [
        { id: "offlineMethod", label: "访问方式", dataType: "singleSelect", required: true, options: [{ label: "街头/商圈拦截", value: "intercept" }, { label: "入户访问", value: "home_visit" }, { label: "门店访问", value: "store_visit" }, { label: "电话访问", value: "telephone" }, { label: "产品测试", value: "product_test" }] },
        { id: "sampleSize", label: "有效样本量", dataType: "number", unit: "份", required: true },
        { id: "cityCount", label: "覆盖城市", dataType: "number", unit: "个", required: true },
        { id: "executionDays", label: "现场执行天数", dataType: "number", unit: "天", required: true },
        { id: "interviewerCount", label: "访问员人数", dataType: "number", unit: "人", required: true },
        { id: "incentiveResponsibility", label: "受访者礼金", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "venueResponsibility", label: "场地与设备", dataType: "singleSelect", required: true, options: responsibilityOptions },
        ...commonWithAudience,
      ],
    },
    {
      id: "in_depth_interview",
      name: "深度访谈",
      shortDescription: "招募、礼金、主持与研究报告的完整预算",
      accent: "#00a785",
      parameters: [
        { id: "interviewCount", label: "访谈人数", dataType: "number", unit: "人", required: true },
        { id: "sessionDurationMinutes", label: "单场时长", dataType: "number", unit: "分钟", required: true },
        { id: "recruitmentDifficulty", label: "招募难度", dataType: "singleSelect", required: true, options: recruitmentOptions },
        { id: "deliveryMode", label: "执行方式", dataType: "singleSelect", required: true, options: [{ label: "线上访谈", value: "online" }, { label: "线下访谈", value: "offline" }, { label: "混合执行", value: "hybrid" }] },
        { id: "incentiveResponsibility", label: "受访者礼金", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "recordingResponsibility", label: "录音录像", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "transcriptResponsibility", label: "逐字稿", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "travelResponsibility", label: "异地差旅", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "cityCount", label: "覆盖城市", dataType: "number", unit: "个", required: true },
        ...commonWithAudience,
      ],
    },
    {
      id: "focus_group",
      name: "焦点小组/座谈会",
      shortDescription: "按场次、参会人数和场地要求精细测算",
      accent: "#f08a41",
      parameters: [
        { id: "sessionCount", label: "座谈会场次数", dataType: "number", unit: "场", required: true },
        { id: "participantsPerSession", label: "每场参会人数", dataType: "number", unit: "人", required: true },
        { id: "backupParticipantsPerSession", label: "每场备用人数", dataType: "number", unit: "人", required: false },
        { id: "sessionDurationMinutes", label: "单场时长", dataType: "number", unit: "分钟", required: true },
        { id: "recruitmentDifficulty", label: "招募难度", dataType: "singleSelect", required: true, options: recruitmentOptions },
        { id: "deliveryMode", label: "执行方式", dataType: "singleSelect", required: true, options: [{ label: "线下座谈会", value: "offline" }, { label: "线上焦点小组", value: "online" }, { label: "混合执行", value: "hybrid" }] },
        { id: "incentiveResponsibility", label: "受访者礼金", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "venueResponsibility", label: "场地与设备", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "observationResponsibility", label: "观察室/单面镜", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "recordingResponsibility", label: "录音录像", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "liveStreamingResponsibility", label: "远程直播", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "translationResponsibility", label: "翻译/同声传译", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "transcriptResponsibility", label: "逐字稿", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "travelResponsibility", label: "异地差旅", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "cityCount", label: "覆盖城市", dataType: "number", unit: "个", required: true },
        ...commonWithAudience,
      ],
    },
    {
      id: "expert_interview",
      name: "专家访谈",
      shortDescription: "专家招募、礼金、访谈与洞察报告预算",
      accent: "#c260a1",
      parameters: [
        { id: "expertCount", label: "专家访谈人数", dataType: "number", unit: "人", required: true },
        { id: "expertIndustry", label: "专家所属行业", dataType: "text", required: true },
        { id: "expertLevel", label: "专家职位级别", dataType: "singleSelect", required: true, options: [{ label: "专业人员/中层", value: "manager" }, { label: "部门负责人/高层", value: "director" }, { label: "企业高管/权威专家", value: "executive" }] },
        { id: "expertScarcity", label: "专家稀缺度", dataType: "singleSelect", required: true, options: [{ label: "常规行业专家", value: "standard" }, { label: "资深或细分领域专家", value: "scarce" }, { label: "高管或极稀缺专家", value: "rare" }] },
        { id: "sessionDurationMinutes", label: "单场时长", dataType: "number", unit: "分钟", required: true },
        { id: "expertHonorariumResponsibility", label: "专家礼金", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "recordingResponsibility", label: "录音录像", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "transcriptResponsibility", label: "逐字稿", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "travelResponsibility", label: "异地差旅", dataType: "singleSelect", required: true, options: responsibilityOptions },
        ...commonWithAudience,
      ],
    },
    {
      id: "desk_research",
      name: "桌面研究",
      shortDescription: "公开资料、行业数据库与研究人天综合预算",
      accent: "#7a6fd1",
      parameters: [
        { id: "researchTopic", label: "研究主题", dataType: "text", required: true },
        { id: "geographicScope", label: "国家或地区范围", dataType: "text", required: true },
        { id: "sourceCount", label: "预计信息源数量", dataType: "number", unit: "个", required: true },
        { id: "databaseResponsibility", label: "行业数据库/数据购买", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "expertSupplement", label: "需要专家补充", dataType: "boolean", required: false },
        { id: "expertSupplementCount", label: "补充专家人数", dataType: "number", unit: "人", required: true, visibleWhen: { field: "expertSupplement", equals: true } },
        { id: "expertScarcity", label: "补充专家稀缺度", dataType: "singleSelect", required: true, visibleWhen: { field: "expertSupplement", equals: true }, options: [{ label: "常规行业专家", value: "standard" }, { label: "资深或细分领域专家", value: "scarce" }, { label: "高管或极稀缺专家", value: "rare" }] },
        ...deliveryCommon,
      ],
    },
    {
      id: "mixed_research",
      name: "综合研究项目",
      shortDescription: "定量、定性、专家与桌面研究模块组合报价",
      accent: "#7d58d6",
      parameters: [
        { id: "qualitativeMethods", label: "研究模块", description: "可同时选择多个研究模块", dataType: "multiSelect", required: true, options: [{ label: "线上定量研究", value: "quantitative_online" }, { label: "深度访谈", value: "in_depth_interview" }, { label: "焦点小组/座谈会", value: "focus_group" }, { label: "专家访谈", value: "expert_interview" }, { label: "桌面研究", value: "desk_research" }] },
        { id: "sampleSize", label: "定量样本量", dataType: "number", unit: "份", required: true, visibleWhen: { field: "qualitativeMethods", includes: "quantitative_online" } },
        { id: "incidenceRate", label: "目标人群筛选通过率", dataType: "percentage", unit: "%", required: true, visibleWhen: { field: "qualitativeMethods", includes: "quantitative_online" } },
        { id: "provinceCount", label: "线上定量覆盖省份", dataType: "number", unit: "个", required: true, visibleWhen: { field: "qualitativeMethods", includes: "quantitative_online" } },
        { id: "interviewCount", label: "深访人数", dataType: "number", unit: "人", required: true, visibleWhen: { field: "qualitativeMethods", includes: "in_depth_interview" } },
        { id: "sessionDurationMinutes", label: "单场时长", dataType: "number", unit: "分钟", required: true, visibleWhen: { field: "qualitativeMethods", includes: "in_depth_interview" } },
        { id: "sessionCount", label: "座谈会场次数", dataType: "number", unit: "场", required: true, visibleWhen: { field: "qualitativeMethods", includes: "focus_group" } },
        { id: "participantsPerSession", label: "每场参会人数", dataType: "number", unit: "人", required: true, visibleWhen: { field: "qualitativeMethods", includes: "focus_group" } },
        { id: "backupParticipantsPerSession", label: "每场备用人数", dataType: "number", unit: "人", required: false, visibleWhen: { field: "qualitativeMethods", includes: "focus_group" } },
        { id: "deliveryMode", label: "座谈会执行方式", dataType: "singleSelect", required: true, visibleWhen: { field: "qualitativeMethods", includes: "focus_group" }, options: [{ label: "线下座谈会", value: "offline" }, { label: "线上焦点小组", value: "online" }, { label: "混合执行", value: "hybrid" }] },
        { id: "expertCount", label: "专家访谈人数", dataType: "number", unit: "人", required: true, visibleWhen: { field: "qualitativeMethods", includes: "expert_interview" } },
        { id: "expertScarcity", label: "专家稀缺度", dataType: "singleSelect", required: true, visibleWhen: { field: "qualitativeMethods", includes: "expert_interview" }, options: [{ label: "常规行业专家", value: "standard" }, { label: "资深或细分领域专家", value: "scarce" }, { label: "高管或极稀缺专家", value: "rare" }] },
        { id: "sourceCount", label: "桌面研究信息源数量", dataType: "number", unit: "个", required: true, visibleWhen: { field: "qualitativeMethods", includes: "desk_research" } },
        { id: "recruitmentDifficulty", label: "定性招募难度", dataType: "singleSelect", required: true, options: recruitmentOptions },
        { id: "incentiveResponsibility", label: "普通受访者礼金", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "expertHonorariumResponsibility", label: "专家礼金", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "databaseResponsibility", label: "行业数据库/数据购买", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "venueResponsibility", label: "场地与设备", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "recordingResponsibility", label: "录音录像", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "transcriptResponsibility", label: "逐字稿", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "travelResponsibility", label: "异地差旅", dataType: "singleSelect", required: true, options: responsibilityOptions },
        { id: "cityCount", label: "覆盖城市", dataType: "number", unit: "个", required: true },
        ...commonWithAudience,
      ],
    },
  ],
};

const allTypes: ResearchProjectTypeId[] = ["quantitative_online", "quantitative_offline", "in_depth_interview", "focus_group", "expert_interview", "desk_research", "mixed_research"];

export const defaultPriceBook: PriceBookConfig = {
  version: 2,
  updatedAt: "2026-07-18T00:00:00.000Z",
  items: [
    { id: "design", name: "研究设计", unit: "项", costUnitPriceCents: 300000, suggestedSaleUnitPriceCents: 500000, saleUnitPriceMinCents: 400000, saleUnitPriceMaxCents: 800000, applicableProjectTypes: allTypes, sensitive: false },
    { id: "sample", name: "线上样本执行", unit: "份", costUnitPriceCents: 1800, suggestedSaleUnitPriceCents: 3000, saleUnitPriceMinCents: 2200, saleUnitPriceMaxCents: 5000, applicableProjectTypes: ["quantitative_online", "mixed_research"], sensitive: true },
    { id: "offline_execution", name: "线下访问执行", unit: "份", costUnitPriceCents: 6500, suggestedSaleUnitPriceCents: 10000, saleUnitPriceMinCents: 8000, saleUnitPriceMaxCents: 18000, applicableProjectTypes: ["quantitative_offline"], sensitive: true },
    { id: "interviewer", name: "访问员执行", unit: "人天", costUnitPriceCents: 50000, suggestedSaleUnitPriceCents: 80000, saleUnitPriceMinCents: 65000, saleUnitPriceMaxCents: 120000, applicableProjectTypes: ["quantitative_offline"], sensitive: true },
    { id: "field_supervision", name: "现场督导", unit: "城市", costUnitPriceCents: 120000, suggestedSaleUnitPriceCents: 200000, saleUnitPriceMinCents: 160000, saleUnitPriceMaxCents: 300000, applicableProjectTypes: ["quantitative_offline"], sensitive: true },
    { id: "data_entry", name: "数据录入与质检", unit: "份", costUnitPriceCents: 1200, suggestedSaleUnitPriceCents: 2000, saleUnitPriceMinCents: 1500, saleUnitPriceMaxCents: 3500, applicableProjectTypes: ["quantitative_offline"], sensitive: false },
    { id: "recruit", name: "受访者招募", unit: "人", costUnitPriceCents: 22000, suggestedSaleUnitPriceCents: 35000, saleUnitPriceMinCents: 28000, saleUnitPriceMaxCents: 65000, applicableProjectTypes: ["in_depth_interview", "focus_group", "mixed_research"], sensitive: true },
    { id: "incentive", name: "用户礼金", unit: "人", costUnitPriceCents: 30000, suggestedSaleUnitPriceCents: 30000, saleUnitPriceMinCents: 20000, saleUnitPriceMaxCents: 80000, applicableProjectTypes: ["quantitative_offline", "in_depth_interview", "focus_group", "mixed_research"], sensitive: true },
    { id: "moderation", name: "主持与执行", unit: "场", costUnitPriceCents: 180000, suggestedSaleUnitPriceCents: 300000, saleUnitPriceMinCents: 250000, saleUnitPriceMaxCents: 600000, applicableProjectTypes: ["in_depth_interview", "focus_group", "expert_interview", "mixed_research"], sensitive: true },
    { id: "venue", name: "场地与设备", unit: "场", costUnitPriceCents: 250000, suggestedSaleUnitPriceCents: 350000, saleUnitPriceMinCents: 250000, saleUnitPriceMaxCents: 800000, applicableProjectTypes: ["quantitative_offline", "focus_group", "mixed_research"], sensitive: true },
    { id: "observation_room", name: "观察室/单面镜", unit: "场", costUnitPriceCents: 100000, suggestedSaleUnitPriceCents: 160000, saleUnitPriceMinCents: 120000, saleUnitPriceMaxCents: 300000, applicableProjectTypes: ["focus_group", "mixed_research"], sensitive: true },
    { id: "recording", name: "专业录音录像", unit: "场", costUnitPriceCents: 60000, suggestedSaleUnitPriceCents: 100000, saleUnitPriceMinCents: 80000, saleUnitPriceMaxCents: 180000, applicableProjectTypes: ["in_depth_interview", "focus_group", "mixed_research"], sensitive: false },
    { id: "live_streaming", name: "远程直播", unit: "场", costUnitPriceCents: 50000, suggestedSaleUnitPriceCents: 90000, saleUnitPriceMinCents: 70000, saleUnitPriceMaxCents: 160000, applicableProjectTypes: ["focus_group", "mixed_research"], sensitive: false },
    { id: "translation", name: "翻译/同声传译", unit: "场", costUnitPriceCents: 180000, suggestedSaleUnitPriceCents: 280000, saleUnitPriceMinCents: 220000, saleUnitPriceMaxCents: 500000, applicableProjectTypes: ["focus_group", "mixed_research"], sensitive: true },
    { id: "transcript", name: "录音与逐字稿", unit: "场", costUnitPriceCents: 50000, suggestedSaleUnitPriceCents: 80000, saleUnitPriceMinCents: 50000, saleUnitPriceMaxCents: 150000, applicableProjectTypes: ["in_depth_interview", "focus_group", "expert_interview", "mixed_research"], sensitive: false },
    { id: "travel", name: "异地差旅预留", unit: "项", costUnitPriceCents: 300000, suggestedSaleUnitPriceCents: 350000, saleUnitPriceMinCents: 300000, saleUnitPriceMaxCents: 800000, applicableProjectTypes: ["in_depth_interview", "focus_group", "mixed_research"], sensitive: true },
    { id: "expert_recruit", name: "专家招募", unit: "人", costUnitPriceCents: 80000, suggestedSaleUnitPriceCents: 150000, saleUnitPriceMinCents: 100000, saleUnitPriceMaxCents: 300000, applicableProjectTypes: ["expert_interview", "mixed_research"], sensitive: true },
    { id: "expert_honorarium", name: "专家礼金", unit: "人", costUnitPriceCents: 150000, suggestedSaleUnitPriceCents: 150000, saleUnitPriceMinCents: 100000, saleUnitPriceMaxCents: 500000, applicableProjectTypes: ["expert_interview", "mixed_research"], sensitive: true },
    { id: "desk_sources", name: "资料检索与信息源整理", unit: "个", costUnitPriceCents: 5000, suggestedSaleUnitPriceCents: 9000, saleUnitPriceMinCents: 7000, saleUnitPriceMaxCents: 16000, applicableProjectTypes: ["desk_research", "mixed_research"], sensitive: false },
    { id: "database_access", name: "行业数据库与数据购买", unit: "项", costUnitPriceCents: 300000, suggestedSaleUnitPriceCents: 350000, saleUnitPriceMinCents: 300000, saleUnitPriceMaxCents: 1000000, applicableProjectTypes: ["desk_research", "mixed_research"], sensitive: true },
  ],
  laborRoles: [
    { id: "director", name: "研究总监", costPerDayCents: 300000, suggestedSalePerDayCents: 500000, salePerDayMinCents: 400000, salePerDayMaxCents: 800000 },
    { id: "senior_manager", name: "高级研究经理", costPerDayCents: 220000, suggestedSalePerDayCents: 360000, salePerDayMinCents: 300000, salePerDayMaxCents: 550000 },
    { id: "manager", name: "研究经理", costPerDayCents: 160000, suggestedSalePerDayCents: 260000, salePerDayMinCents: 220000, salePerDayMaxCents: 400000 },
    { id: "assistant", name: "助理经理及以下", costPerDayCents: 90000, suggestedSalePerDayCents: 150000, salePerDayMinCents: 120000, salePerDayMaxCents: 250000 },
  ],
};
